Create ProblemsMotivations.md
zkSNACKs/WasabiDesign pull request #13
Opened 2020-04-28 15:39 UTC by molnard

2020-05-02 00:13 UTC, yahiheb requested changes

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +This is a list that collets problems and motivations related crypto wallets in general. This is not focusing on a specific implementation.
```suggestion
This is a list that collects problems and motivations related to crypto wallets in general. This is not focusing on a specific implementation.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +While we already have a working wallet it is worth to get back to the basics and re-evaluate: **What are the problems we want to solve in real life with a crypto wallet?**
```suggestion
While we already have a working wallet it is important to get back to the basics and re-evaluate: **What are the problems we want to solve in real life with a crypto wallet?**
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- What is your the biggest problem?
```suggestion
- What is your biggest problem?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- Tell me your 3 most annoying problems?
```suggestion
- What is your top three most annoying problems?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- How it is different from traditional banking system?
```suggestion
- How is it different from the traditional banking system?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I cannot use the softwares, don't know what to do there.
```suggestion
- I cannot use the software, I don't know what to do there.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- How much fiat do I have currenly in my wallet?
```suggestion
- How much fiat do I have currently in my wallet?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I am not sure that I am doing things in a proper way. My workflow is good or not?
```suggestion
- I am not sure that I am doing things in a proper way. Is my workflow good or not?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- What happens if I lost my device or stolen?
```suggestion
- What happens if I lose my device or it gets stolen?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I am not sure that I have writted down correcly my mnemonics and stored it in a safe way.
```suggestion
- I am not sure that I have written down correctly my mnemonics and stored it in a safe way.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I don't know what kind of private infomations am I sharing with who, when I am using a wallet. (comparison table)
```suggestion
- I don't know what kind of private information am I sharing with who, when I am using a wallet. (comparison table)
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I have to verify a lot of numbers when copy/paste bitcoin addresses, scary.
```suggestion
- I have to verify a lot of characters when I copy/paste bitcoin addresses, which is scary.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- Different units used those are unknows sats, bitcoin.
```suggestion
- Different units used that are unknown sats, bitcoin.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- Unknown and not standardized terms used in different softwares.
```suggestion
- Unknown and not standardized terms used in different software.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I have to send my address every time I receive, complicated.
```suggestion
- I have to send my address every time I receive, complicated.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I want to have only one wallet even among devices (mobile phone and desktop)
```suggestion
- I want to have only one wallet even among devices (mobile phone and desktop).
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I have to test the wallet in live with real money. What if I do something wrong and loose that money?
```suggestion
- I have to test the wallet in live with real money. What if I do something wrong and lose that money?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I had to study bitcoin before the usage, learning curve.
```suggestion
- I had to study Bitcoin before using it, learning curve.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- Interoperatibility between different wallets, bisq?
```suggestion
- Interoperability between different wallets, bisq?
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I am not sure that I have backed up my wallet properly.
```suggestion
- I am not sure that I have backed up my wallet properly.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- Badly designed wallets. They are ugly.
```suggestion
- I don't know the exact fees.
- Confirmation time and fees how is it related.

- Badly designed wallets. They are ugly.
```

2020-05-02 00:13 UTC, yahiheb commented on ProblemsMotivations.md
> +- I want my financial privacy back.
```suggestion
- I want to store my money.
- I want my financial privacy back.
```

2020-05-02 07:53 UTC, MaxHillebrand commented on ProblemsMotivations.md
> +- How much fiat do I have currenly in my wallet?
```suggestion
- How much are the bitcoin in my wallet currently worth in fiat?
```

2020-05-02 07:54 UTC, MaxHillebrand commented on ProblemsMotivations.md
> +- I don't understand, I don't speak english.
```suggestion
- I don't understand specific terminology.
- I don't speak english.
```

2020-05-02 07:55 UTC, MaxHillebrand commented on ProblemsMotivations.md
> +
```suggestion

- How can I segregate my transaction history?
```

2020-05-03 17:17 UTC, molnard commented
Thx @yahiheb and @MaxHillebrand

2020-05-03 17:17 UTC, merged